[package]
name = "tu_cdb_types"
version = "0.1.0"
edition = "2018"

[lib]
name = "tu_cdb_types"
path = "lib.rs"

[dependencies]
marine-rs-sdk = "0.7.1"
serde = { version = "1.0.152", features = ["derive"] }