[package]
name = "composedb_adapter"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "composedb_adapter"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = "0.7.1"
serde = "1.0.152"

[dev-dependencies]
marine-rs-sdk-test = "0.8.1"